// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGaPdJIPgpkSjd7ClkqHHJqk4eh0ec__Q',
    appId: '1:335785605903:web:3e0faa94e54d9a405cdc7a',
    messagingSenderId: '335785605903',
    projectId: 'learning-cdss',
    authDomain: 'learning-cdss.firebaseapp.com',
    storageBucket: 'learning-cdss.appspot.com',
    measurementId: 'G-E2QC7GVQJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYj2KVFzq7ejfUKa3lsg3Tt_2mBNTMMQU',
    appId: '1:335785605903:android:079e103415138d095cdc7a',
    messagingSenderId: '335785605903',
    projectId: 'learning-cdss',
    storageBucket: 'learning-cdss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0As9hNCIVvtjSS8qLSSIgpYrxva_L9ME',
    appId: '1:335785605903:ios:670a8e902b38fbfc5cdc7a',
    messagingSenderId: '335785605903',
    projectId: 'learning-cdss',
    storageBucket: 'learning-cdss.appspot.com',
    iosClientId: '335785605903-j6qcob9v8pbonhnugrh2mb0m2cdo0h3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningCdss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0As9hNCIVvtjSS8qLSSIgpYrxva_L9ME',
    appId: '1:335785605903:ios:670a8e902b38fbfc5cdc7a',
    messagingSenderId: '335785605903',
    projectId: 'learning-cdss',
    storageBucket: 'learning-cdss.appspot.com',
    iosClientId: '335785605903-j6qcob9v8pbonhnugrh2mb0m2cdo0h3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningCdss',
  );
}
